//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trabajo2Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Hobby = new HashSet<Hobby>();
        }
    
        public int clientId { get; set; }
        public string DNI { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public int sex { get; set; }
        public string description { get; set; }
        public int cityId { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<Hobby> Hobby { get; set; }
    }
}
